name: snap_edit
description: A concept app with simple functionality for editing images.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.9
  zoom_widget: ^2.0.1
  font_awesome_flutter: ^10.4.0
  path_provider: ^2.0.15
  permission_handler: ^10.3.0
  dio: ^5.2.1+1
  screenshot: ^2.1.0
  signature: ^5.4.0
  flutter_colorpicker: ^1.0.3
  image_gallery_saver: ^2.0.2
  ficonsax: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/ProductSans-Black.ttf
          weight: 900
        - asset: assets/fonts/ProductSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/ProductSans-Light.ttf
          weight: 300
        - asset: assets/fonts/ProductSans-Thin.ttf
          weight: 100